### PR TITLE
Added CIDR block overlap check

### PR DESCRIPTION
**Pull request by r2dedios**
Related to: submariner-io/enhancements#64

### CODE REVIEW

**Comment by dfarrell07** [comment]
Thanks for the PR @r2dedios! I allowed the CI to run, and as you can see it's flagging a few issues for you.

**Comment by r2dedios** [comment]
Hi @dfarrell07,

Yes, I saw them, thanks. I will update this PR with some tests trying to use the same testing framework. This is related with @ruromero 's PR (https://github.com/submariner-io/cloud-prepare/pull/190)

I will notice you when this PR would be finished

**Comment by dfarrell07** [comment]
Okay, thanks @r2dedios! If this is WIP and not ready for review, you may want to mark it as a draft: https://submariner.io/development/code-review/#mark-work-in-progress-prs-as-drafts

**Comment by ruromero** [comment]
@dfarrell07 we will join this commit and other related to the linked PR so that we have it all together in the same PR

**Pull request closed without merging**
