### PR TITLE
Add support for HA

### PR DESCRIPTION
**Pull request by mkolesnik**
Add support for deploying more than one gateway node

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Review by aswinsuryan — APPROVED** [review]

**Review by mangelajo — APPROVED** [review]

**Review by mangelajo — COMMENTED** [review]
Looks good, we need to add the linter & unit testing to this repo at least ;D

**Review by nyechiel — APPROVED** [review]

**Comment by mkolesnik** [comment]
Folded #4 into this one since both are approved

**Comment by mkolesnik** [comment]
Has to rebase locally and force push it, the commits are exactly the same as they were

**Pull request merged**
